### ISSUE TITLE
Confusing text in session 2

### ISSUE THREAD

**Issue by ericozzi** [railsmn/project-schedule-old-obsolete#11]
"At this point, restart your Rails server for the model changes to take effect. Now you can run commands like user.tasks to get all of the users tasks or task.user to find the owner of a task. For more information on model associations, check out the Rails guide on Active Record associations"

This reads that I should be able to execute or run a "command" called user.tasks. Rather, this means that you can use these references in code.

**Comment by westonplatter** [comment]
Thanks @ericozzi for the 2nd pair of eyes on our wording. I changed "run commands" to "user associations" via https://github.com/railsmn/schedule/commit/7e52b71d0c9870c4e9bd0450951a562e4fdea022. 

Does that remove the confusing wording? See whole paragraph below. 

> At this point, restart your Rails server for the model changes to take effect. Now you can use associations like
>  `user.tasks` to get all of the users tasks or `task.user` to find the owner of a task. For more information
> on model associations, check out [the Rails guide on Active Record associations](http://guides.rubyonrails.org/association_basics.html)

**Comment by ericozzi** [comment]
Looks good to me!

Eric

**Comment by westonplatter** [comment]
@ericozzi sweet. closing.
