### ISSUE TITLE
Show path link typo

### ISSUE THREAD

**Issue by linkalis** [railsmn/project-schedule-old-obsolete#12]
This...
<% link_to 'Show', note_path(note) %>

...should read like this:
<%= link_to 'Show', note_path(note) %>

**Comment by westonplatter** [comment]
@linkalis - you're on fire. Thanks for 2nd pair of eyes. Fixed via - https://github.com/railsmn/schedule/commit/a9a6d0e773caf41f8db2d17a61d62f6ba9be24a7
