### ISSUE TITLE
Edit path link typo

### ISSUE THREAD

**Issue by linkalis** [railsmn/project-schedule-old-obsolete#14]
This...
<% link_to 'Edit', edit_note_path(note) %>

...should read like this:
<%= link_to 'Edit', edit_note_path(@note) %>

**Comment by westonplatter** [comment]
@linkalis - where are you seeing this? Is it here https://github.com/railsmn/schedule/blame/master/open_camp/session1.md#L606?

**Comment by westonplatter** [comment]
@linkalis - ah, I now I see what you mean. Fixed via - https://github.com/railsmn/schedule/commit/a9a6d0e773caf41f8db2d17a61d62f6ba9be24a7
