### ISSUE TITLE
Session 2 plans

### ISSUE THREAD

**Issue by westonplatter** [railsmn/project-schedule-old-obsolete#3]
outline = 
1. welcome - we're happy you're here
2. short recap from session 1
3. VM update, we moved to Ruby 2.0, `git pull origin master`.
4. Hack Session
4a. Authentication with Devise
4b. Unit Testing with Rspec
5. Lightning Talks
5a. TDD
5b. Capybara
5c. Git

**Comment by derekrockwell** [comment]
I created the high level skeleton of the session2.md file. Would you like to start filling in the details for the hack session?

**Comment by westonplatter** [comment]
We wrote session 2. Closing.
